#workspace 'PROJECTS.xcworkspace'
#project 'PROJECTS.xcodeproj'

platform:ios,'8.0'

inhibit_all_warnings!

target 'PROJECTS' do
    
    pod 'SDWebImage','~>4.1.2'
    pod 'Masonry','~>1.1.0'
    pod 'IQKeyboardManager','~>5.0.4'
    pod 'MJExtension','~>3.0.13'
    pod 'MJRefresh','~>3.1.14'
    pod 'MBProgressHUD','~>1.0.0'
    pod 'FMDB','~>2.7.2'
    pod 'JPush','~>3.0.6'
    pod 'UMengAnalytics','~>4.2.4'
    pod 'Bugly','~>2.4.8'
    pod 'AliPay','~>2.1.2'
    
#    高德地图
    pod 'AMap3DMap','~>5.4.0'
    pod 'AMapLocation','~>2.4.0'
    pod 'AMapSearch','~>5.4.0'
    
#    全部AFNetworking
#    pod 'AFNetworking'
#    定制AFNetworking
    pod 'AFNetworking/Serialization','~>3.1.0'
    pod 'AFNetworking/Security','~>3.1.0'
    pod 'AFNetworking/Reachability','~>3.1.0'
    pod 'AFNetworking/NSURLSession','~>3.1.0'
    
end
